import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/providers/CartContext";
import { TimeContextProvider } from "@/providers/TimeContext";
import Footer from "../components/ui/footer";
import ToastProvider from "@/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bar e Hamburgueria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <ToastProvider>
            <TimeContextProvider>
              <CartContextProvider>
                <div className="flex-1 pb-12">{children}</div>

                <Footer />
              </CartContextProvider>
            </TimeContextProvider>
          </ToastProvider>
        </div>
      </body>
    </html>
  );
}
